server:
  port: 8083
spring:
  application:
    name: message-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.168.3/sc-dev-file?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  # Zipkin 配置项，对应 ZipkinProperties 类
  zipkin:
    base-url: ${sc.zipkin.base-url} # Zipkin 服务的地址
    discovery-client-enabled: false # 让 nacos 把它当作一个 url，而不是服务
  # Spring Cloud Sleuth 配置项
  sleuth:
    # Spring Cloud Sleuth 针对 Web 组件的配置项，例如说 SpringMVC
    web:
      enabled: true # 是否开启，默认为 true
    sampler:
      probability: 1.0 # 采样百分比
  cloud:
    nacos:
      discovery:
        server-addr: ${sc.nacos.discovery.server-addr}
    # Spring Cloud Stream 配置项，对应 BindingServiceProperties 类
    stream:
      # Binding 配置项，对应 BindingProperties Map
      bindings:
        message-service-input:
          destination: DOCUMENT-MESSAGE-TOPIC # 目的地。这里使用 RocketMQ Topic
          content-type: application/json # 内容格式。这里使用 JSON
          group: message-center-group # 消费者分组
          # Consumer 配置项，对应 ConsumerProperties 类
          consumer:
            # 禁用 Spring Cloud Stream 提供的重试功能，使用 RocketMQ 提供的重试功能
            max-attempts: 1
      # Spring Cloud Stream RocketMQ 配置项
      rocketmq:
        # RocketMQ Binder 配置项，对应 RocketMQBinderConfigurationProperties 类
        binder:
          name-server: ${sc.rocketmq.name-server} # RocketMQ Namesrv 地址
        # RocketMQ 自定义 Binding 配置项，对应 RocketMQBindingProperties Map
        bindings:
          message-service-input:
            # RocketMQ Consumer 配置项，对应 RocketMQConsumerProperties 类
            consumer:
              enabled: true # 是否开启消费，默认为 true
              broadcasting: false # 是否使用广播消费，默认为 false 使用集群消费
              delay-level-when-next-consume: 0 # 异步消费消息模式下消费失败重试策略，默认为 0

  mail:
    # 邮件服务地址
    host: smtp.qq.com
    # 端口,可不写默认 25
    port:
    # 编码格式
    default-encoding: utf-8
    # 用户名
    username: 1442803701@qq.com
    # 授权码，就是我们刚才准备工作获取的代码
    password:
    # 其它参数
    properties:
      mail:
        smtp:
          # 如果是用 SSL 方式，需要配置如下属性,使用qq邮箱的话需要开启
          ssl:
            enable: true
            required: true
          # 邮件接收时间的限制，单位毫秒
          timeout: 10000
          # 连接时间的限制，单位毫秒
          connectiontimeout: 10000
          # 邮件发送时间的限制，单位毫秒
          writetimeout: 10000