server:
  port: 8080

spring:
  application:
    name: sc-gateway
  cloud:
    nacos:
      discovery:
            server-addr: ${sc.nacos.discovery.server-addr}
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: route_user
#          uri: http://localhost:8084
#          order: 1
#          predicates:
#            - Path=/user-service/**
#          filters:
#            - StripPrefix=1

feign:
  sentinel:
    enabled: true

# logging
logging:
  level:
    # dao 开启 debug 模式 mybatis 输入 sql
    com:
      scmp:
        file:
            mybatis:
              mapper: debug