server:
  port: 8084

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sc-dev?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 13518360063
  cloud:
    nacos:
      discovery:
#        server-addr: ${sc.nacos.discovery.server-addr}
        server-addr: 127.0.0.1:8848

mybatis:
  configuration:
    map-underscore-to-camel-case: true