server:
  port: 8081
spring:
  application:
    name: document-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.168.3/sc-dev-file?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  # Zipkin 配置项，对应 ZipkinProperties 类
  zipkin:
    base-url: ${sc.zipkin.base-url} # Zipkin 服务的地址
    discovery-client-enabled: false # 让 nacos 把它当作一个 url，而不是服务
  # Spring Cloud Sleuth 配置项
  sleuth:
    # Spring Cloud Sleuth 针对 Web 组件的配置项，例如说 SpringMVC
    web:
      enabled: true # 是否开启，默认为 true
    sampler:
      probability: 1.0 # 采样百分比
  cloud:
    nacos:
      discovery:
        server-addr: ${sc.nacos.discovery.server-addr}
    stream:
      # Binding 配置项，对应 BindingProperties Map
      bindings:
        document-service-output:
          destination: DOCUMENT-MESSAGE-TOPIC # 目的地。这里使用 RocketMQ Topic
          content-type: application/json # 内容格式。这里使用 JSON
      # Spring Cloud Stream RocketMQ 配置项
      rocketmq:
        # RocketMQ Binder 配置项，对应 RocketMQBinderConfigurationProperties 类
        binder:
          name-server: ${sc.rocketmq.name-server} # RocketMQ Namesrv 地址
        # RocketMQ 自定义 Binding 配置项，对应 RocketMQBindingProperties Map
        bindings:
          document-service-output:
            # RocketMQ Producer 配置项，对应 RocketMQProducerProperties 类
            producer:
              group: document-producer-group # 生产者分组
              sync: false # 是否同步发送消息，默认为 false 异步
feign:
  sentinel:
    enabled: true
